# Generated by Django 4.1.4 on 2023-01-04 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordsmodel',
            options={'verbose_name': 'Пароль для доступа к хранилищу', 'verbose_name_plural': 'Пароли для доступа к хранилищу'},
        ),
        migrations.AlterField(
            model_name='passwordsmodel',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль для доступа к хранилищу'),
        ),
        migrations.CreateModel(
            name='PasswordStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords_store', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пароль пользователя',
                'verbose_name_plural': 'Пароли пользователя',
            },
        ),
    ]
