# Generated by Django 4.1.4 on 2023-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_store', '0002_alter_passwordsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordstoremodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='passwordstoremodel',
            name='email',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='passwordstoremodel',
            name='username',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Имя пользователя'),
        ),
    ]
