# Generated by Django 4.1.4 on 2023-01-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_store', '0004_alter_passwordsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
